# Generated by Django 6.0.1 on 2026-01-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_ui", "0002_loadgroup_load_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="missing_refs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
