# Generated by Django 6.0.1 on 2026-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_ui", "0003_alter_load_missing_refs"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="is_fnd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="load",
            name="is_na",
            field=models.BooleanField(default=False),
        ),
    ]
