# Generated by Django 6.0.1 on 2026-02-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_ui", "0005_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loads",
                to="warehouse_ui.shift",
            ),
        ),
        migrations.AddField(
            model_name="loadgroup",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="warehouse_ui.shift",
            ),
        ),
    ]
